# Generated by Django 2.2.7 on 2019-11-24 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Response',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mturk_id', models.CharField(default='None', max_length=50)),
                ('algorithm', models.CharField(max_length=10)),
                ('query', models.CharField(max_length=100)),
                ('rating', models.PositiveSmallIntegerField()),
                ('time_spent', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='browser_info',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='age',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='education',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='ip_address',
            field=models.CharField(default='0.0.0.0', max_length=50),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='mturk_id',
            field=models.CharField(default='None', max_length=50, primary_key=True, serialize=False),
        ),
    ]
